/**
 * LLM 模块统一导出
 */

export {
  generateStory,
  generateFaceToFaceJointDialogues,
  generateCgPrompt,
  generateMiniTheater,
  generateCharacterSpeech,
  generateCardContent,
  generatePhoneSmsReply,
  generateGroupChatReply,
  generateDormChatReply,
  generatePhoneCallReply,
  generatePhoneMomentsReplies,
  generatePhoneMomentsBatchReplies,
  generatePhoneForumPosts,
  generatePhoneNewsFeed,
  generatePhoneMapData,
  generatePhoneShopItems,
  generateDormShopItems,
  generateTaskBoardTasks,
  generateDormItemGiftReply,
  generateCharacterVisit,
  generateCharacterDiary,
  generateRedditPosts,
  generateRedditCommentReplies,
  generateBackpackUseResult,
  generateHandheldBrickLevel,
  generateHandheldPetProfile,
  generateHandheldPetReply,
  generateHandheldDungeonScene,
  generateHandheldDungeonMap,
  generateHandheldDungeonBanter,
  generateHandheldCampfireCompanions,
  generateWorldBookOpeningDialogue,
  generateBedroomFurnitureItems,
  generateMerchantItems,
  getActiveApiConfig,
  generateQuizQuestions,
  generateAssessmentQuestions,
  parseUrlContent,
  generateTeachingContent,
  generateTeachingReply,
  gradeAnswer,
  calculateRating,
  generatePronunciationLesson,
  generatePronunciationTTS,
  parsePronunciationOutput,
} from './llmService'
export { buildStoryPrompt, buildQuickPrompt } from './promptGenerator'
export {
  parseStoryContent,
  validateDialogue,
  toGameScript,
  extractHighlightCharacters,
  getEmotionDisplayLabel,
  createDialogueSummary,
  hasChoices,
  extractChoices,
} from './storyParser'
